### ISSUE TITLE
Java Compilation Error

### ISSUE THREAD

**Issue by tnesavich** [signalfx/tracing-examples#110]
Get an "Execution failed for task ':compileJava'. > Could not find tools.jar." error during the [Build the example service](https://github.com/signalfx/tracing-examples/blob/main/profiling/docs/01_getting_started.md#build-the-example-service) section of Part 1 of the profiling workshop that [this post](https://forums.fusetools.com/t/how-to-resolve-jdk-issue-when-building-android-on-macos-big-sur/8114) resolved for me.  I am on Monterey but it still worked to get past that error.

**Comment by breedx-splk** [comment]
Hi @tnesavich. I recommended that you file this issue so that we can track it. I am worried about this solution, however, of copying JVM internal components (like `tools.jar`) between potentially different JVM vendors and/or versions. This could create an inconsistent (and likely unsupported) JVM configuration.

The original problem was likely caused by a broken/incomplete `$PATH` env var or broken/missing `$JAVA_HOME` env var. 

I now recommend reinstalling your JDK and trying again, making sure that you have `JAVA_HOME` defined in your shell environment and that you have java in your path.  Let us know how it goes. ☮️

**Comment by breedx-splk** [comment]
Examples now live here: https://github.com/open-telemetry/opentelemetry-java-examples. Please give it a vist.
